kind: pipeline
name: default

steps:
- name: build
  image: node:latest
  commands: 
  - npm install   
- name: docker  
  image: plugins/docker
  settings:
    repo: estones7/beacon
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

